---
version: 1.0.{build}

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019
  - ubuntu1604
  - ubuntu1804
  - Ubuntu

environment:
  PERL5LIB: /home/appveyor/perl5/lib/perl5
  AUTOMATED_TESTING: 1
  # TEST_VERBOSE: 1
  DEBIAN_FRONTEND: noninteractive
  PERL_MM_USE_DEFAULT: 1

platform: x64

branches:
  only:
    - master

skip_tags: true

install:
  - cmd: if not exist "C:\strawberry" cinst StrawberryPerl --allow-empty-checksums
  - cmd: path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  # - cmd: cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - sh: sudo apt-get update -q -y
  - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get install -q -y --force-yes build-essential git libssl-dev perl
  - sh: export PATH=/home/appveyor/perl5/bin:$PATH
  - perl -V
  - cmd: mkdir %APPVEYOR_BUILD_FOLDER%\tmp
  - cmd: set TMPDIR=%APPVEYOR_BUILD_FOLDER%\tmp
  - cpan App::cpanminus
  - cmd: cpanm -q --showdeps --with-develop --with-suggests . | findstr /v "^perl\>" | cpanm -qin --skip-satisfied
  - cpanm -qin --skip-satisfied --installdeps .
  - cmd: 'echo End install at: & time /t'

build_script:
  - perl Makefile.PL

test_script:
  - cmd: gmake test
  - sh: make test
